### ISSUE TITLE
The last part of ToolChain tutorial is a bit confusing.

### ISSUE THREAD

**Issue by laporchen** [aokblast/Computer_Programming_II_111#5]
In the end of ToolChain tutorial
```
To run CMake, we use the following command:

cd target
cmake ..
```
I think it will be confusing for students that why do you need to change directory to target.

**Comment by aokblast** [comment]
In previous section, we put all artifact and result into target directory. So for consistency, we put all of the artifact and result in target directory too.

**Comment by laporchen** [comment]
I think `cmake --build "./target"` should be more easier to understand.

**Comment by aokblast** [comment]
I think the latest commit solve this issue. If I am right, we can close this issue.

**Comment by laporchen** [comment]
That will work. I think it is very clear on what you want to do there now.
